### ISSUE TITLE
Create RSM HCD Nuget Organization

### ISSUE THREAD

**Issue by rllowman** [rsm-hcd/AndcultureCode.CSharp#54]
Create a new NuGet organization for RSM HCD. Name: `rsm-hcd`

**Comment by rllowman** [comment]
Broken off from #52

**Comment by rllowman** [comment]
Quick Q for discussion: What should we do with the old [`andculture`](https://www.nuget.org/profiles/andculture) NuGet org? Should we preserve the org or take it down? If we leave the org up, should we consider [deprecating/unlisting](https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages) the packages?

**Comment by myty** [comment]
I'd say we leave as is.  Delisting, could potentially break anything that is currently depending on those versions.

**Comment by rllowman** [comment]
Maybe we could deprecate the packages and point folks to the newer org, similar to what we're doing with GitHub?

**Comment by myty** [comment]
If that's an option, let's go for it.

**Comment by myty** [comment]
Added an organizational secret, `NUGET_RSM_AUTH_TOKEN`.  When the packages are updated in the repo and we are ready to publish, we can update the GH publish action to use the new token. 

![Image](https://github.com/rsm-hcd/AndcultureCode.CSharp/assets/37794/641c4eb4-4a79-404a-bbf8-e477e01f3ff1)
